# Generated by Django 6.1.1 on 2026-09-10 11:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retiree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('position', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('date_hired', models.DateField()),
                ('date_retired', models.DateField()),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiary_name', models.CharField(blank=True, max_length=160)),
                ('beneficiary_relationship', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'In Review'), ('active', 'Active')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PensionComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_service', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_per_year', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), max_digits=5)),
                ('base_pension', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_monthly_pension', models.DecimalField(decimal_places=2, max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('retiree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computations', to='retirees.retiree')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('award', 'Certificate of Pension Award'), ('service', 'Service Record Certificate'), ('computation', 'Computation Slip'), ('clearance', 'Clearance Certificate')], max_length=20)),
                ('certificate_no', models.CharField(max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('retiree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='retirees.retiree')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
